import OpenAI from 'openai';
import { z } from 'zod';

let openai: OpenAI | null = null;

function getOpenAI() {
  if (!openai) {
    if (!process.env.OPENAI_API_KEY) {
      throw new Error('OPENAI_API_KEY environment variable is required');
    }
    openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }
  return openai;
}

const RepurposedContentSchema = z.object({
  x: z.object({
    thread: z.array(z.string()).length(3)
  }),
  ig: z.object({
    carousel: z.array(z.string()).length(3)
  }),
  fb: z.object({
    post: z.string(),
    poll: z.string()
  })
});

export type RepurposedContent = z.infer<typeof RepurposedContentSchema>;

export async function repurposeContent(originalText: string): Promise<RepurposedContent> {
  const prompt = `You are a content repurposer for "Learn AI with Ife" – inspirational AI/tech posts. From this LinkedIn text: ${originalText}. Generate JSON only:

{
  "x": {
    "thread": ["Tweet 1: Hook + #AIEngineer", "Tweet 2: Tip", "Tweet 3: CTA question"]
  },
  "ig": {
    "carousel": ["Slide 1: Quote graphic text", "Slide 2: Tip", "Slide 3: Call to action"]
  },
  "fb": {
    "post": "Adapted text for discussion",
    "poll": "Question for engagement?"
  }
}

Keep concise, engaging, tone: Professional yet motivational. Max 280 chars/tweet/slide.`;

  try {
    const openaiClient = getOpenAI();
    const response = await openaiClient.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.7,
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error('No content generated by OpenAI');
    }

    const parsedContent = JSON.parse(content);
    const validatedContent = RepurposedContentSchema.parse(parsedContent);
    
    return validatedContent;
  } catch (error) {
    console.error('Error repurposing content:', error);
    throw new Error('Failed to repurpose content');
  }
}